#pragma once

enum OBJID { MAP, PLAYER, MONSTER, EFFECT, COLLISIONOBJ, PORTAL, GRAVE,MON_ATT, MON_CLOSEATT, PLAYER_ATT,BOSS_ATT, PLAYER_CLOSEATT,
	PLAYER_HPBAR, PLAYER_STATE, BOSS_HPBAR, BOSS_STATE, OBJ_END };

enum SCENE_ID {
	SCENE_LOGO
	, SCENE_TUTORIAL, SCENE_STAGE1, SCENE_STAGE2
	, SCENE_GAMEOVER,SCENE_END
};

