#pragma once

enum OBJID { MAP, PLAYER, MONSTER, EFFECT, COLLISIONOBJ, PORTAL,MON_ATT,OBJ_END };

enum SCENE_ID {
	SCENE_LOGO
	, SCENE_TUTORIAL, SCENE_STAGE1, SCENE_STAGE2
	, SCENE_GAMEOVER,SCENE_END
};

